checkpoint:
  state_dict_type: sharded
  chkpt_saving_steps: 1000      # Set to null to disable checkpointing during debugging
  preempt_metadata_path: preempt/convnext-training
  preempt_chkpt_saving_steps: 100  # Set to null to disable preemptive checkpointing during debugging
  directory: experiments/chkpts
  prefix: convnext-training
  path_chkpt_prev: null
  offload_to_cpu: false
  rank0_only: false

dataset:
  drop_last_in_sampler: true
  drop_last_in_loader: true
  batch_size: 2
  num_workers: 2
  pin_memory: true
  prefetch_factor: 20
  path_train: experiments/datasets/peaknet_dataset.train.csv  
  path_eval: experiments/datasets/peaknet_dataset.validate.csv
  debug: false
  cache_size: 10
  # Cross-rank shuffling configuration
  enable_shuffling_train: true   # Enable shuffling for training dataset
  enable_shuffling_eval: false   # Keep evaluation deterministic
  shuffle_seed_base: 42          # Base seed for deterministic shuffling
  reshuffle_frequency: 10        # Steps between reshuffles (0 = no reshuffling)
  transforms:
    H_pad: 1920
    W_pad: 1920
    Hv: 256
    Wv: 256
    sigma: 0.333
    num_crop: 8
    set:
      pad: true
      polar_center_crop: true
      random_patch: false
      random_rotate: false
      random_shift: false
      batch_sampler: false

dist:
  backend: nccl
  uses_unique_world_seed: true
  dtype: bfloat16
  cpu_offload: null

logging:
  directory: experiments/logs
  prefix: convnext-training
  level: INFO

loss:
  grad_accum_steps: 4
  focal:
    alpha: [0.25, 0.75]
    gamma: 2.0

lr_scheduler:
  min_lr: 1.0e-07
  total_steps: 1000000  # 1M steps for training
  warmup_steps: 1000
  scheduler_update_steps: 1

misc:
  max_eval_iter: 10
  max_eval_retry: 2
  sharding_stage: zero3
  compiles_model: false
  data_dump_on: false
  cpu_only: false
  peak_flops_per_sec: 312000000000000.0
  monitors_dynamics: true

model:
  from_scratch: true
  backbone:
    hf_config:
      num_channels: 1
      patch_size: 4
      num_stages: 4
      hidden_sizes: [96, 192, 384, 768]
      depths: [3, 3, 9, 3]
      hidden_act: "gelu"
      initializer_range: 0.02
      layer_norm_eps: !!float 1e-12
      drop_path_rate: 0.0
      image_size: 256
      out_features: ['stage1', 'stage2', 'stage3', 'stage4']
      out_indices: null
  bifpn:
    block:
      base_level: 4
      bn:
        eps: !!float 1.0e-05
        momentum: 0.1
      down_scale_factor: 0.5
      fusion:
        eps: !!float 1.0e-05
      num_features: 256
      num_levels: 4
      relu_inplace: false
      up_scale_factor: 2
    num_blocks: 1
  seg_head:
    base_scale_factor: 2
    num_classes: 2
    num_groups: 32
    out_channels: 256
    up_scale_factor:
    - 4
    - 8
    - 16
    - 32
    uses_learned_upsample: false

optim:
  grad_clip: 1.0
  lr: !!float 1.5e-4
  weight_decay: !!float 0.05
  beta1: 0.9
  beta2: 0.95
  fused: false